version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: always
    command: mongod --bind_ip 0.0.0.0
volumes:
  mongodb-data:
